services:
  web:
    image: node:22.12.0
    user: node
    working_dir: /home/node/web
    volumes:
      - "./:/home/node/web"
    ports:
      - "3000:3000"
    entrypoint: ["./docker-entrypoint.sh"]
    command: "npm run dev"
